accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
    path('signup/', views.SignupView.as_view(), name='account_signup'),
]

app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('room/<int:year>/<int:month>/<int:day>', views.RoomView.as_view(), name='room'),
    # path('room/<int:pk>', views.StaffView.as_view(), name='staff'),
    path('calendar/<int:pk>', views.CalendarView.as_view(), name='calendar'),
    path('calendar/<int:pk>/<int:year>/<int:month>/<int:day>', views.CalendarView.as_view(), name='calendar'),
    path('booking/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>', views.BookingView.as_view(), name='booking'),
    path('thanks', views.ThanksView.as_view(), name='thanks'),
    path('mypage/<int:pk>/', views.MyPageView.as_view(), name='mypage'),
    # path('mypage/<int:year>/<int:month>/<int:day>/', views.MyPageView.as_view(), name='mypage'),
    # path('mypage/holiday/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Holiday, name='holiday'),
    # path('mypage/delete/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Delete, name='delete'),
    path('mypage/delete/<int:pk>/', views.Delete, name='delete'),
]

pj_meetingroom3/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from allauth.account import views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    #サインアップメール認証設定
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.utils import timezone
from django.core.mail import send_mail


class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('メールアドレス', unique=True)
    first_name = models.CharField('姓', max_length=30)
    last_name = models.CharField('名', max_length=30)
    department = models.CharField('所属', max_length=30, blank=True)
    created = models.DateField('入会日', default=timezone.now)
    description = models.TextField('自己紹介', default="", blank=True)
    image = models.ImageField(upload_to='images', verbose_name='プロフィール画像', null=True, blank=True)

    is_staff = models.BooleanField(
        ('staff status'),
        default=False,
        help_text=('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        ('active'),
        default=True,
        help_text=(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from allauth.account.forms import SignupForm

#サインアップ用フォーム保存完了時に認証メールを送信
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
# from .models import CustomUser
from django.contrib.auth import get_user_model
CustomUser = get_user_model()


class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='姓')
    last_name = forms.CharField(max_length=30, label='名')
    description = forms.CharField(label='自己紹介', widget=forms.Textarea(), required=False)
    image = forms.ImageField(required=False, )


class SignupUserForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='姓')
    last_name = forms.CharField(max_length=30,  label='名')

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user


#サインアップメール送信設定
subject = "登録確認"
message_template = """
ご登録ありがとうございます。
以下URLをクリックして登録を完了してください。

"""
#サインアップメール送信設定
def get_activate_url(user):
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    return settings.FRONTEND_URL + "/activate/{}/{}/".format(uid, token)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')
    
    def save(self, commit=True):
        # commit=Falseだと、DBに保存されない
        user = super().save(commit=False)
        # user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data["email"]
        # user.password1 = self.cleaned_data['password1']
        # user.password2 = self.cleaned_data['password2']

        # 確認するまでログイン不可にする
        user.is_active = False

        if commit:
            user.save()
            activate_url = get_activate_url(user)
            message = message_template + activate_url
            # from_email = "admin@itc.tokyo"
            # recipient_list =["test@itc.tokyo"]
            user.email_user(subject, message)
        return user


#サインアップメール認証設定
def activate_user(uidb64, token):    
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = CustomUser.objects.get(pk=uid)
    except Exception:
        return False

    if default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return True
    
    return False

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from accounts.models import CustomUser
from accounts.forms import ProfileForm, SignupUserForm
from allauth.account import views
from django.contrib.auth.mixins import LoginRequiredMixin

#サインアップメール認証設定
from django.views.generic import TemplateView
from .forms import activate_user, CustomUserCreationForm
from django.urls import reverse_lazy


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = CustomUser.objects.get(id=request.user.id)

        return render(request, 'accounts/profile.html', {
            'user_data': user_data,
        })


class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = CustomUser.objects.get(id=request.user.id)
        form = ProfileForm(
            request.POST or None,
            initial = {
                'first_name': user_data.first_name,
                'last_name': user_data.last_name,
                'description': user_data.description,
                'image': user_data.image
            }
        )

        return render(request, 'accounts/profile_edit.html', {
            'form': form 
        })

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            user_data = CustomUser.objects.get(id=request.user.id)
            user_data.first_name = form.cleaned_data['first_name']
            user_data.last_name = form.cleaned_data['last_name']
            user_data.description = form.cleaned_data['description']
            if request.FILES.get('image'):
                user_data.image = request.FILES.get('image')
            user_data.save()
            return redirect('accounts:profile')

        return render(request, 'accounts/profile.html', {
            'form': form,
        })


class LoginView(views.LoginView):
    template_name = 'accounts/login.html'


class LogoutView(views.LogoutView):
    template_name = 'accounts/logout.html'

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            self.logout()
        # return redirect('/')
        return redirect('account_login')

class SignupView(views.SignupView):
    template_name = 'accounts/signup.html'
    # form_class = SignupUserForm
    #サインアップメール認証設定
    form_class = CustomUserCreationForm
    # success_url = reverse_lazy('account_login')


#サインアップメール認証設定
class ActivateView(TemplateView):
    template_name = "accounts/activate.html"
    
    def get(self, request, uidb64, token, *args, **kwargs):
        # 認証トークンを検証して、
        result = activate_user(uidb64, token)
        # コンテクストのresultにTrue/Falseの結果を渡します。
        return super().get(request, result=result, **kwargs)

accounts/templates/accounts/activate.html
{% extends "app/base.html" %}
{% block content %}

{% if result %}
    <p>認証に成功しました。</p>
    <p><a href="{% url 'accounts:account_login' %}">ログイン</a></p>
{% else %}
    <p>無効なリンクです。</p>
{% endif %}

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{%  block content %}

<div class="card card-auth my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">ログイン</h5>
        <form method="post" class="form-auth">
            {% csrf_token %}
            <div class="formm-label-group">
                {% render_field form.login class='form-control' placeholder='メールアドレス' %}
            </div>
            <div class="formm-label-group">
                {% render_field form.password class='form-control' placeholder='パスワード' %}
            </div>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit" >ログイン</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'app/base.html' %}

{% block content %}

<div class="card card-auth my-5 mx-auto">
    <div class="card-body">
        <p class="card-title text-center">ログアウトしますか？</p>
        <form method="post" class="form-auth">
            {% csrf_token %}
            <div class="button mx-auto">
                <button class="btn btn-lg btn-warning btn-block mx-auto" type="submit">ログアウト</buttom>
            </div>
        </form>
    </div>
</div>

</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'app/base.html' %}

{% block content %}

<card class="card-profile my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">プロフィール</h5>
        <table class="profile_table mb-4">
            <tbody>
                <tr>
                    <th class="header">プロフィール画像</th>
                    <td class="data">
                        {% if user_data.image %}
                            <img src="{{ user_data.image.url }}" alt="" width="100px">
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th class="header">名前</th>
                    <td class="data">{{ user_data.first_name }} {{user_data.last_name}}</td>
                </tr>
                <tr>
                    <th class="header">メールアドレス</th>
                    <td class="data">{{ user_data.email }}</td>
                </tr>
                <tr>
                    <th class="header">自己紹介</th>
                    <td class="data">{{ user_data.description }}</td>
                </tr>
            </tbody>
        </table>
        <div class="button mx-auto">
            <a href="{% url 'accounts:profile_edit' %}" class="btn btn-lg btn-warning btn-block">編集する</a>
        </div>
    </div>
</card>

{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <div class="card-title text-center">プロフィール</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="profile_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">プロフィール画像</th>
                        <td class="data">
                            {{ form.image }}
                        </td>
                    </tr>
                    <tr>
                        <th class="header">名前</th>
                        <td class="data form_wrap form_wrap-2">
                            {% render_field form.first_name class='form-control' placeholder='姓' %}
                            {% render_field form.last_name class='form-control' placeholder='名' %}
                        </td>
                    </tr>
                    <tr>
                        <th class="header">自己紹介</th>
                        <td class="data">
                            {% render_field form.description class='form-control' placeholder='自己紹介' %}
                    </tr>
                </tbody>
            </table>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-warning btn-block" type="submit">登録する</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="card card-auth my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">サインアップ</h5>
        <form method="post" class="form-auth">
            {% csrf_token %}
            <div class="form-label-group form_wrap form_wrap-2">
                {% render_field form.first_name class='form-control' placeholder='姓' %}
                {% render_field form.last_name class='form-control' placeholder='名' %}
            </div>
            <div class="form-label-group">
                {% render_field form.email class='form-control' placeholder='メールアドレス' %}
            </div>
            <div class="form-label-group">
                {% render_field form.password1 class='form-control' placeholder='パスワード' %}
            </div>
            <div class="form-label-group">
                {% render_field form.password2 class='form-control' placeholder='パスワード(確認)' %}
            </div>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">サインアップ</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}