accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
    path('signup/', views.SignupView.as_view(), name='account_signup'),
]

app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('room/<int:year>/<int:month>/<int:day>', views.RoomView.as_view(), name='room'),
    # path('room/<int:pk>', views.StaffView.as_view(), name='staff'),
    path('calendar/<int:pk>', views.CalendarView.as_view(), name='calendar'),
    path('calendar/<int:pk>/<int:year>/<int:month>/<int:day>', views.CalendarView.as_view(), name='calendar'),
    path('booking/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>', views.BookingView.as_view(), name='booking'),
    path('thanks', views.ThanksView.as_view(), name='thanks'),
    path('mypage/<int:pk>/', views.MyPageView.as_view(), name='mypage'),
    # path('mypage/<int:year>/<int:month>/<int:day>/', views.MyPageView.as_view(), name='mypage'),
    # path('mypage/holiday/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Holiday, name='holiday'),
    # path('mypage/delete/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Delete, name='delete'),
    path('mypage/delete/<int:pk>/', views.Delete, name='delete'),
]

pj_meetingroom3/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from allauth.account import views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    #サインアップメール認証設定
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>予約サイト</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="/" class="navbar-brand">予約サイト</a>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="/" class="nav-link">ホーム</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'app:mypage' user.pk %}" class="nav-link">マイページ</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:profile' %}" class="nav-link">プロフィール</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_logout' %}" class="nav-link">ログアウト</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_signup' %}" class="nav-link">スタッフ</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_login' %}" class="nav-link">ログイン</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <style>
        footer {
            width: 100%;
            height: 40px;
            line-height: 30px;
        }
    </style>

    <footer id='footer' class="py-2 bg-dark">
        <p class="m-0 text-center text-white">Copyright &copy; Shuji Hasegawa</p>
    </footer>

    {% block extra-js %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <script>
        $(function(){
        //フッターを最下部に固定
            var $footer = $('#footer');
            if(window.innerHeight > $footer.offset().top + $footer.outerHeight() ) {
                $footer.attr({'style': 'position:fixed; top:' + (window.innerHeight - $footer.outerHeight()) + 'px;' });
            }
        })
    </script>

</body>
</html>

app/templates/app/booking.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}


<div class="card card-booking my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">予約内容</h5>
        <table class="booking_table mb-4">
            <tbody>
                <tr>
                    <th class="header">会議室</th>
                    <td class="data">{{ room_data.name }}</td>
                </tr>
                <tr>
                    <th class="header">スタッフ</th>
                    <td class="data">{{ staff_data.user.first_name }} {{ staff_data.user.last_name }}</td>
                </tr>
                <tr>
                    <th class="header">日程</th>
                    <td class="data">
                        {% for error in form.non_field_errors %}
                            <h5 class="text-danger">{{ error|linebreaksbr }}</h5>
                        {% endfor %}
                        {{ year }}年{{ month }}月{{ day }}日 {{ hour }}:00
                    </td>
                </tr>
            </tbody>
        </table>
        <h5 class="card-title text-center">予約情報</h5>
        <form method="post">
            {% csrf_token %}
            <table class="booking_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">利用者名</th>
                        <td class="data form_wrap form_wrap__2col">
                            {% render_field form.first_name class='form-control' placeholder='姓' %}
                            {% render_field form.last_name class='form-control' placeholder='名' %}
                        </td>
                    </tr>
                    <tr>
                        <th class="header">その他備考</th>
                        <td class="data">
                            {% render_field form.remarks class='form-control' placeholder='利用目的及び特記事項' %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-warning btn-block" type="submit">予約確定</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

app/templates/app/month copy.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                    {% if month_current.month != day.month %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day | date:"m/d" }}
                        </a>
                    {% else %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day.day }}
                        </a>
                    {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/month.html
{% extends 'app/base.html' %}

{% block content %}
<h4><div class="text-center my-1">カレンダー</div></h4>
    <div class="text-center my-2 mb-3">
        <a href="{% url 'app:month' month_previous.year month_previous.month %}" class="btn btn-warning">前月</a>
        {{ month_current | date:"Y年m月" }}
        <a href="{% url 'app:month' month_next.year month_next.month %}" class="btn btn-warning">次月</a>
    </div>
    <div class="">
        <table class="table table-bordered bg-light">
            <thead class="thead-light">
            <tr>
                {% for weekName in week_names %}
                    {% if weekName == '土' %}
                        <th scope="col" class="text-center text-primary">{{ weekName }}</th>
                    {% elif weekName == '日' %}
                        <th scope="col" class="text-center text-danger">{{ weekName }}</th>
                    {% else %}
                        <th scope="col" class="text-center">{{ weekName }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="text-center table-success" width="100">
                    {% else %}
                        <td class="text-center" width="100">
                    {% endif %}

                    {% if month_current.month != day.month %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day | date:"m/d" }}
                        </a>
                    {% else %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day.day }}
                        </a>
                    {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/month_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
<h4><div class="text-center my-1">カレンダー</div></h4>
<div class="text-center my-2 mb-3">
    <a href="{% url 'app:month_with_schedule' month_previous.year month_previous.month %}" class="btn btn-warning">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month_with_schedule' month_next.year month_next.month %}" class="btn btn-warning">次月</a>
</div>
<div class="">
    <table class="table table-bordered bg-light">
        <thead class="thead-light">
        <tr>
            {% for weekName in week_names %}
                {% if weekName == '土' %}
                    <th scope="col" class="text-center text-primary">{{ weekName }}</th>
                {% elif weekName == '日' %}
                    <th scope="col" class="text-center text-danger">{{ weekName }}</th>
                {% else %}
                    <th scope="col" class="text-center">{{ weekName }}</th>
                {% endif %}
            {% endfor %}
        </tr>
        </thead>
    <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="text-center table-success" width="100">
                    {% else %}
                        <td class="text-center" width="100">
                    {% endif %}

                    {% if month_current.month != day.month %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day | date:"m/d" }}
                        </a>
                        {% for booked in booking_data %}
                            {% if day == booked.start %}
                                {{ booked.remarks }}
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <a href="{% url 'app:room' day.year day.month day.day %}">
                        {{ day.day }}
                        </a>
                        {% for booked in booking_data %}
                        {% if day == booked.start %}
                            {{ booked.remarks }}
                        {% endif %}
                    {% endfor %}

                    {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/mypage copy.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-5">
    <div class="mb-3">
        <h1>予約カレンダー</h1>
        <p>{{ start_day }}~{{ end_day }}</p>
    </div>
    <div class="d-flex mb-2">
        <div class="mx-3 mr-auto">
            <a href="{% url 'mypage' before.year before.month before.day %}" class="btn btn-warning">前週</a>
        </div>
        <div class="mx-3">
            <a href="{% url 'mypage' next.year next.month next.day %}" class="btn btn-warning">次週</a>
        </div>
    </div>
    <div class="mb-3">
        <table class="table-bordered bg-light">
            <thead class="thead-light">
                <tr>
                    <th></th>
                    {% for day in days %}
                        {% if day.weekday == 5 %}
                            <th scope="col" class="text-primary">{{ day | date:'d(D)' }}</th>
                        {% elif day.weekday == 6 %}
                            <th scope="col" class="text-danger">{{ day | date:'d(D)' }}</th>
                        {% else %}
                            <th scope="col">{{ day | date:'d(D)' }}</th>
                        {% endif %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for booking_hour, booking_date in calendar.items %}
                    <tr>
                        <td scope="row">{{ booking_hour }}:00</td>
                        {% for datetime, book in booking_date.items %}
                        <td>
                            {% if book == '' %}
                                <form method="POST" action="{% url 'holiday' datetime.year datetime.month datetime.day booking_hour %}">
                                    {% csrf_token %}
                                    <button class="btn btn-light" type="submit">出勤</button>
                                </form>
                            {% else %}
                                {% if book == None %}
                                    <p class="mb-0">休み</p>
                                {% else %}
                                    <p class="mb-0 font-weight-bold text-success">{{ book }}様</p>
                                {% endif %}
                                <form method="POST" action="{% url 'delete' datetime.year datetime.month datetime.day booking_hour %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">取消</button>
                                </form>
                            {% endif %}
                        </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-md-3 mb-4 text-center mypage">
            <img src="{{ staff_data.user.image.url }}" alt="" class="mb-3 img-fluid">
            <p>{{ staff_data.store.name }}:{{ staff_data.user.first_name }} {{ staff_data.user.last_name }}</p>
        </div>

        <div class="col-md-9 mb-4">
            <div class="card-body px-2 py-1">
                <div class="p-4 text-left">
                    <h3>今週の予約</h3>
                    <hr>
                    <table class="table">
                        <thead class="thead-light">
                            <th>お客様</th>
                            <th>開始時刻</th>
                            <th>終了時刻</th>
                        </thead>
                        <tbody>
                            {% for booking in booking_data %}
                                {% if booking.first_name != None %}
                                    <tr>
                                        <td>{{ booking.first_name }} {{ booking.last_name }}</td>
                                        <td>{{ booking.start }}</td>
                                        <td>{{ booking.end }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/mypage.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-3">

    <div class="mb-3">
        <h3>マイページ<予約確認修正></h1>
        <h5>{{ staff_data.user.first_name }} {{ staff_data.user.last_name }} 様</h5>
    </div>

    <div class="">
        <table class="table table-bordered bg-light">
            <thead class="thead-light">
                <tr>
                    <th class="text-center text-primary">予約番号</th>
                    <th class="text-center text-primary">開始日時</th>
                    <th class="text-center text-primary">終了日時</th>
                    <th class="text-center text-primary">会議室</th>
                    <th class="text-center text-primary">利用者名</th>
                    <th class="text-center text-primary">備考</th>
                    <th class="text-center text-primary">予約取消</th>
                </tr>
            </thead>
            <tbody>
                {% for booked in booking_data %}
                    <tr>
                        <td scope="row">{{ booked.pk }}</td>
                        <td class="text-center" width="auto">{{ booked.start }}</td>
                        <td class="text-center" width="auto">{{ booked.end }}</td>
                        <td class="text-center" width="auto">{{ booked.room }}</td>
                        <td class="text-center" width="auto">{{ booked.first_name }} {{ booked.last_name }}</td>
                        <td class="text-center" width="auto">{{ booked.remarks }}</td>
                        <td class="text-center" width="auto">
                            <form method="post" action="{% url 'app:delete' booked.pk %}">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit">取消</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/app/room copy 2.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-3">

    <div class="mb-3">
        <h1>予約表</h1>
        <h5>{{ year }}年{{ month }}月{{ day }}日{{ dct | date:'(D)' }}</h5>
    </div>
    <div class="d-flex mb-2">
        <div class="mx-3 mr-auto">
            <a href="{% url 'app:room' before.year before.month before.day %}" class="btn btn-warning">前日</a>
        </div>
        <div class="mx-3">
            <a href="{% url 'app:room' next.year next.month next.day %}" class="btn btn-warning">翌日</a>
        </div>
    </div>
    <div class="">
        <table class="table table-bordered bg-light">
            <thead class="thead-light">
                <tr>
                    <th class="text-center text-primary" width="auto">時間</th>
                    {% for room in room_data %}
                            <th scope="col" class="text-primary">{{ room }}</th>
                    {% endfor %}
            </thead>
            <tbody>
                {% for hour, schedules in calendar.items %}
                    <tr>
                        <td scope="row">{{ hour }}:00</td>
                        {% for roomdate, book in schedules.items %}
                            <td>
                                {% if book  %}
                                <a href='{% url "app:booking" roomdate.0.pk roomdate.1.year roomdate.1.month roomdate.1.day hour %}'>
                                    <i class="far fa-circle text-info"></i>
                                </a>
                                {% else %}
                                    <i class="fas fa-times text-danger"></i>
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/app/room copy.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-5">

    <div class="mb-3">
        <h1>予約カレンダー</h1>
        <p>{{ year }}年{{ month }}月{{ day }}日 </p>
    </div>

    <div class="">
        <table class="table table-bordered bg-light">
            <thead class="thead-light">
                <tr>
                    <th></th>
                    {% for room in room_data %}
                            <th scope="col" class="text-primary">{{ room }}</th>
                    {% endfor %}
            </thead>
            <tbody>
                {% for hour, schedules in calendar.items %}
                    <tr>
                        <td scope="row">{{ hour }}:00</td>
                        {% for datetime, book in schedules.items %}
                            <td>
                                {% if book %}
                                    <a href='{% url "app:booking" room_data.id datetime.year datetime.month datetime.day hour %}'>
                                        <i class="far fa-circle text-info"></i>                                        
                                    </a>
                                {% else %}
                                    <i class="fas fa-times text-danger"></i>
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/app/room.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-3">

    <div class="mb-1">
        <h3>予約表</h1>
    </div>
    <div class="text-center my-2 mb-3">
            <a href="{% url 'app:room' before.year before.month before.day %}" class="btn btn-warning">前日</a>
            {{ year }}年{{ month }}月{{ day }}日{{ dct | date:'(D)' }}
            <a href="{% url 'app:room' next.year next.month next.day %}" class="btn btn-warning">翌日</a>
    </div>
    </div>
    <div class="">
        <table class="table table-bordered bg-light">
            <thead class="thead-light">
                <tr>
                    <th class="text-center text-primary" width="auto">時間</th>
                    {% for room in room_data %}
                            <th scope="col" class="text-center text-primary">{{ room }}</th>
                    {% endfor %}
            </thead>
            <tbody class="text-center">
                {% for hour, schedules in calendar.items %}
                    <tr>
                        <td scope="row">{{ hour }}:00</td>
                        {% for roomdate, book in schedules.items %}
                            <td>
                                {% if book == '' %}
                                <a href='{% url "app:booking" roomdate.0.pk roomdate.1.year roomdate.1.month roomdate.1.day hour %}'>
                                    <i class="far fa-circle text-info"></i>
                                </a>
                                {% else %}
                                    <div class="text-danger">{{ book }}</div>
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/app/thanks.html
{% extends 'app/base.html' %}


{% block content %}

<div class="text-center my-5">
    <h1 class="mb-5">ご予約完了</h1>
    <p class="mb-2">予約の確認と取消は画面右上のマイページからおこなってください</p>
    <p class="mb-4">予約を修正したい場合は予約の取消後に再度ホームから始めてください</p>
    <a href="/" class="btn btn-primary">ホームに戻る</a>
</div>


{% endblock %}